repos:
#-   repo: https://github.com/PyCQA/bandit
    #rev: '' # Update me!
    #hooks:
    #- id: bandit

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
      args: [--check, --diff]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ''
    hooks:
    - id: flake8

#-   repo: https://github.com/pre-commit/mirrors-isort
    #rev: ''  # Use the revision sha / tag you want to point at
    #hooks:
    #-   id: isort
        #args: [--check-only, --diff]
